### ISSUE TITLE
support selecting a non-default subtitle track

### ISSUE THREAD

**Issue by be6ana** [dhleong/vlc-video-view#3]
Hi,
how can i implement selecting a non-default subtitle track?

Thank you

**Comment by dhleong** [comment]
Honestly I haven't touched this in years but since it's a wrapper around VLC you might be able to look up whatever option VLC has for doing this and pass it to the `setVideoUri` method? There *is* a TODO [here](https://github.com/dhleong/vlc-video-view/commit/cc5eea007751defdc2a0a7ce7f11a8ec6a6cde39#diff-64924266f51a69b44c18a4a3737ae27ef2ce5213d3af62b33eba1869f3ec968bR259) however so if you want to get your hands dirty and fork this library, you probably would want to enhance this method somewhere there.
